import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/ui/components/navbar";
import { AllProviders } from "@/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`w-screen h-screen ${inter.className} bg-gray-100`}>
        <div className="w-full">
          <AllProviders>
            <Navbar />
            <div className="w-full">{children}</div>
          </AllProviders>
        </div>
      </body>
    </html>
  );
}
